# Generated by Django 4.0 on 2022-09-14 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character https://www.isbn-international.org/content/what-isbn', max_length=13, verbose_name='ISBN')),
                ('total_copies', models.IntegerField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='books')),
                ('available_copies', models.IntegerField()),
            ],
        ),
    ]
